
#image: docker.vahanus.com/ubuntu-dlang-dev:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - if command -v docker ; then echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin docker.vahanus.com ; fi

stages:
- lint
- build
- deploy

lint-program:
  tags:
  - gitlabshell
  - docker
  stage: lint
  script:
  - echo "linting $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  - dub fetch dscanner
  - dub run dscanner -- --report source

build-program:
  tags:
  - gitlabshell
  - docker
  stage: build
  script:
  - echo "building $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  - dub build
  - dub build -b ddox

test-program:
  tags:
  - gitlabshell
  - docker
  stage: build
  script:
  - echo "building $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  - dub test

test-arm-gitlabshell:
  tags:
  - arm-gitlabshell
  - docker
  stage: build
  script:
  - echo "building $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  - docker pull arm64v8/alpine:latest
  - docker images

test-arm-gitlabdocker:
  image: arm64v8/alpine:latest
  tags:
  - arm-gitlabdocker
  stage: build
  script:
  - echo "building $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  - ls /

deploy-program:
  tags:
  - gitlabshell
  - docker
  stage: deploy
  script:
  - echo "cleaning $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  when: manual
