
# Doesn't work due to CA cert issue...
#image: docker.vahanus.com/ubuntu-dlang-dev:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - echo "Working on $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  - if command -v docker ; then echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin docker.vahanus.com ; fi

stages:
  - lint
  - build
  - deploy

#----------------------------------------------------------------------

lint-program:
  tags:
    - gitlabshell
    - docker
  stage: lint
  script:
    - echo "linting $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
    - dub fetch dscanner
    - dub run dscanner -- --report source

#----------------------------------------------------------------------

build-program:
  tags:
    - gitlabshell
    - docker
  stage: build
  script:
    - dub build
    - dub build -b ddox

test-program:
  tags:
    - gitlabshell
    - docker
  stage: build
  script:
    - dub test

#----------------------------------------------------------------------

test-arm-gitlabshell:
  tags:
    - arm-gitlabshell
    - docker
  stage: build
  script:
    - docker pull arm64v8/alpine:latest
    - docker run arm64v8/alpine:latest ls -R /
    - docker images
    - echo "Running within an Alpine Container on ARM !"

test-arm-gitlabdocker:
  image: arm64v8/alpine:latest
  tags:
    - arm-gitlabdocker
  stage: build
  script:
    - ls -R /
    - echo "Running within an Alpine Container on ARM !"

#----------------------------------------------------------------------

deploy-program:
  tags:
    - gitlabshell
    - docker
  stage: deploy
  script:
    - echo "Deploy!"
  when: manual
