
# Doesn't work due to CA cert issue...
#image: docker.vahanus.com/ubuntu-dlang-dev:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - echo "Working on $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
  - if command -v docker ; then echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin docker.vahanus.com ; fi

stages:
  - lint
  - build
  - docs
  - test
  - deploy

#----------------------------------------------------------------------

lint-program:
  tags:
    - gitlabshell
    - docker
  stage: lint
  script:
    - echo "linting $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
    - dub fetch dscanner
    - dub run dscanner -- --report source

#----------------------------------------------------------------------

build-program-x86:
  tags:
    - gitlabshell
    - docker
  stage: build
  script:
    - dub build

build-program-arm:
  tags:
    - arm-gitlabshell
    - docker
  stage: build
  script:
    - dub build

#----------------------------------------------------------------------

test program-x86:
  tags:
    - gitlabshell
    - docker
  stage: test
  script:
    - dub test

test program-arm:
  tags:
    - arm-gitlabshell
    - docker
  stage: test
  script:
    - dub test

#----------------------------------------------------------------------

build docs:
  tags:
    - gitlabshell
    - docker
  stage: docs
  script:
    - dub build -b ddox

#----------------------------------------------------------------------

test-arm64v8-gitlabshell:
  tags:
    - arm-gitlabshell
    - docker
  stage: test
  allow_failure: true
  script:
    - docker pull arm64v8/alpine:latest
    - docker run arm64v8/alpine:latest ls -R /
    - docker pull arm64v8/ubuntu:18.04
    - docker run arm64v8/ubuntu:18.04 ls -R /
    - docker pull arm64v8/debian:latest
    - docker run arm64v8/debian:latest ls -R /
    - docker images
    - echo "Running in SHELL on ARM !"

test-arm64v8-gitlabdocker:
  image: arm64v8/alpine:latest
  tags:
    - arm-gitlabdocker
  stage: test
  allow_failure: true
  script:
    - ls -R /
    - echo "Running within an Alpine Container on ARM !"

test-arm32v7-gitlabshell:
  tags:
    - arm-gitlabshell
    - docker
  stage: test
  allow_failure: true
  script:
    - docker pull arm32v7/alpine:latest
    - docker run arm32v7/alpine:latest ls -R /
    - docker pull arm32v7/ubuntu:18.04
    - docker run arm32v7/ubuntu:18.04 ls -R /
    - docker pull arm32v7/debian:latest
    - docker run arm32v7/debian:latest ls -R /
    - docker images
    - echo "Running in SHELL on ARM !"

test-arm32v7-gitlabdocker:
  image: arm32v7/alpine:latest
  tags:
    - arm-gitlabdocker
  stage: test
  allow_failure: true
  script:
    - ls -R /
    - echo "Running within an Alpine Container on ARM !"

#----------------------------------------------------------------------

deploy-program:
  tags:
    - gitlabshell
    - docker
  stage: deploy
  script:
    - echo "Deploy!"
  when: manual
