
# Doesn't work due to CA cert issue...
#image: docker.vahanus.com/ubuntu-dlang-dev:latest

stages:
  - lint
  - build
  - docs
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal

#----------------------------------------------------------------------

default:
  # Use Ubuntu-based dev image with some D compilers and dub installed
  image: "gitlab.vahanus.net:5050/vahanus/public/container-ubuntu-dlang-dev:latest"
  before_script:
    - command -v docker && docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY || true
    - command -v docker && docker info || true

#----------------------------------------------------------------------

lint-program:
  tags:
    - gitlabdocker
  stage: lint
  allow_failure: true
  script:
    - echo "linting $CI_COMMIT_REF_NAME / $CI_COMMIT_SHA ..."
    #- dub fetch dscanner
    #- dub run dscanner -- --report source
    - dub lint

#----------------------------------------------------------------------

build-program-x86:
  tags:
    - gitlabdocker
  stage: build
  script:
    - dub build

build-program-arm:
  tags:
    - arm-gitlabshell
    - docker
  allow_failure: true
  stage: build
  script:
    - dub build

#----------------------------------------------------------------------

test program-x86:
  tags:
    - gitlabdocker
  stage: test
  script:
    - dub test

test program-arm:
  tags:
    - arm-gitlabshell
    - docker
  allow_failure: true
  stage: test
  script:
    - dub test

#----------------------------------------------------------------------

build docs:
  tags:
    - gitlabdocker
  stage: docs
  allow_failure: true
  script:
    - dub build -b ddox

#----------------------------------------------------------------------

test-arm64v8-gitlabshell:
  tags:
    - arm-gitlabshell
    - docker
  stage: test
  allow_failure: true
  script:
    - docker pull arm64v8/alpine:latest
    - docker run arm64v8/alpine:latest ls -R /
    - docker pull arm64v8/ubuntu:18.04
    - docker run arm64v8/ubuntu:18.04 ls -R /
    - docker pull arm64v8/debian:latest
    - docker run arm64v8/debian:latest ls -R /
    - docker images
    - echo "Running in SHELL on ARM !"

test-arm64v8-gitlabdocker:
  image: arm64v8/alpine:latest
  tags:
    - arm-gitlabdocker
  stage: test
  allow_failure: true
  script:
    - ls -R /
    - echo "Running within an Alpine Container on ARM !"

test-arm32v7-gitlabshell:
  tags:
    - arm-gitlabshell
    - docker
  stage: test
  allow_failure: true
  script:
    - docker pull arm32v7/alpine:latest
    - docker run arm32v7/alpine:latest ls -R /
    - docker pull arm32v7/ubuntu:18.04
    - docker run arm32v7/ubuntu:18.04 ls -R /
    - docker pull arm32v7/debian:latest
    - docker run arm32v7/debian:latest ls -R /
    - docker images
    - echo "Running in SHELL on ARM !"

test-arm32v7-gitlabdocker:
  image: arm32v7/alpine:latest
  tags:
    - arm-gitlabdocker
  stage: test
  allow_failure: true
  script:
    - ls -R /
    - echo "Running within an Alpine Container on ARM !"

#----------------------------------------------------------------------

deploy-program:
  tags:
    - gitlabdocker
  stage: deploy
  script:
    - echo "Deploy!"
  when: manual
